# Generated by Django 5.2.6 on 2025-09-24 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название предложения')),
                ('price_original', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена без скидки')),
                ('price_discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена со скидкой')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название партнёра')),
                ('contact', models.CharField(blank=True, max_length=255, verbose_name='Контактная информация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название роли')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='DealCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discounts.category', verbose_name='Категория')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discounts.deal', verbose_name='Предложение')),
            ],
            options={
                'verbose_name': 'Связь предложение-категория',
                'verbose_name_plural': 'Связи предложения-категории',
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='categories',
            field=models.ManyToManyField(through='discounts.DealCategory', to='discounts.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='deal',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discounts.merchant', verbose_name='Партнёр'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('password_hash', models.CharField(max_length=255, verbose_name='Хэш пароля')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='discounts.role', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.AddField(
            model_name='merchant',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discounts.user', verbose_name='Владелец'),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код купона')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('redeemed', 'Погашен'), ('expired', 'Просрочен')], max_length=20, verbose_name='Статус')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('redeemed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата погашения')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discounts.deal', verbose_name='Предложение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discounts.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Купон',
                'verbose_name_plural': 'Купоны',
            },
        ),
    ]
