# Generated by Django 5.2.6 on 2025-09-26 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название предложения')),
                ('price_original', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена без скидки')),
                ('price_discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена со скидкой')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('image_url', models.URLField(blank=True, default='', verbose_name='Картинка (URL)')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код купона')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('redeemed', 'Использован'), ('expired', 'Истёк')], default='active', max_length=20, verbose_name='Статус')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('redeemed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата использования')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discounts.deal', verbose_name='Предложение')),
            ],
            options={
                'verbose_name': 'Купон',
                'verbose_name_plural': 'Купоны',
            },
        ),
        migrations.CreateModel(
            name='DealCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discounts.category')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discounts.deal')),
            ],
            options={
                'verbose_name': 'Категория предложения',
                'verbose_name_plural': 'Категории предложений',
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='categories',
            field=models.ManyToManyField(through='discounts.DealCategory', to='discounts.category', verbose_name='Категории'),
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название партнёра')),
                ('contact', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Контактный email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discounts.merchant', verbose_name='Партнёр'),
        ),
    ]
