# Generated by Django 5.2.6 on 2025-09-24 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealcategory',
            options={'verbose_name': 'Категория предложения', 'verbose_name_plural': 'Категории предложений'},
        ),
        migrations.AddField(
            model_name='deal',
            name='image_url',
            field=models.URLField(blank=True, default='', verbose_name='Картинка (URL)'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Код купона'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='redeemed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата использования'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('redeemed', 'Использован'), ('expired', 'Истёк')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='dealcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discounts.category'),
        ),
        migrations.AlterField(
            model_name='dealcategory',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discounts.deal'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='contact',
            field=models.CharField(blank=True, max_length=255, verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='discounts.user', verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название роли'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discounts.role', verbose_name='Роль'),
        ),
    ]
