# Generated by Django 5.2.6 on 2025-10-09 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_deal_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_deals', to=settings.AUTH_USER_MODEL, verbose_name='Добавили в избранное'),
        ),
    ]
